#!/usr/bin/env bash

set -Co pipefail

file="$1"
file_extension="${file##*.}"
file_extension="${file_extension@L}"
file_mimetype="$(file --dereference --brief --mime-type -- "${file}")"
file_info="$(file --dereference --brief -- "$file")"

width="$2"
height="$3"

hash() {
    stat --printf "%n\0%i\0%F\0%s\0%W\0%Y" "$(readlink -f "${file}")" |
        sha256sum | awk '{print $1}'
}

image_pv() {
    chafa -f sixel -s "${width}x${height}" --animate off --polite on -t 1 --bg black "${1}"
}

thumbnail_pv() {
    thumbnails_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/lf/thumbnails/"
    thumbnail="${thumbnails_dir}/$(hash).jpg"

    if [ ! -f "$thumbnail" ]; then
        mkdir -p "$thumbnails_dir"

        case "$file_mimetype" in
            application/pdf)
                pdftoppm -singlefile -jpeg "$file" "${thumbnail%%.jpg}" ;;

            video/*)
                ffmpegthumbnailer -s 0 -i "$file" -o "$thumbnail" ;;

            image/svg+xml)
                magick -format jpg -background transparent "$file" "$thumbnail" ;;
        esac
    fi

    image_pv "$thumbnail"
}

# Handle mimetype
case "$file_mimetype" in
    */zip | */java-archive)
        atool --list -- "$file" && exit 1 ;;
    application/pdf | video/* | image/svg+xml)
        thumbnail_pv && exit 1 ;;

    image/*)
        image_pv "$file" && exit 1
        magick identify "$file" && exit 1
        ;;

    audio/*)
        id3v2 -l "$file" | sed 's/^\(id3v. tag info\) for .*/=== \1 ===/' |
            fold -sw "$width" &&
            exit 1
        ;;

    *opendocument*)
        odt2txt "$file" && exit 1 ;;

    text/*|application/json|application/javascript)
        bat --color always --number --decorations always "$file" && exit 1
        fold -sw "$width" "$file" && exit 1
        ;;
esac

printf "%s\n" "=== File Type Classification ===" "$file_info" |
    fold -sw "$width" && exit 1
