#!/usr/bin/env bash

# Verbosity and settings
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    mkdir="mkdir -pv" \
    yt="yt-dlp" \
    yta="yt -x -f bestaudio/best" \
    ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible
alias \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ip="ip -color=auto" \
    ncdu="ncdu --color dark"

# Programs
alias \
    e='nvim -O' \
    nsxiv='nsxiv-rifle' \
    ls='eza --group-directories-first --group --icons=auto' \
    la='ls --all' \
    ll='ls --long' \
    lla='ls --long --all' \
    lt='ls --tree' \
    lta='ls --tree --all' \
    prename='perl-rename' \
    wtr='curl wttr.in/Caracas\?Fq'

# Dotfiles
alias dots='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
