#!/usr/bin/env bash

# Default programs
export BROWSER='firefox'
export EDITOR='nvim'
export DMENU_CMD='rofi -dmenu -i'

# Settings
# Add all directories in `~/.local/bin` to $PATH
localpath=$(find "${HOME}/.local/bin" -type d | paste -sd ':' -)
export PATH="$PATH:$localpath"
export HISTCONTROL='ignoredups'
export QT_QPA_PLATFORMTHEME='gtk3'

export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export INPUTRC="${XDG_CONFIG_HOME}/shell/inputrc"
export XINITRC="${XDG_CONFIG_HOME}/x11/xinitrc"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

[ -z "${WAYLAND_DISPLAY}" ] && [ "${XDG_VTNR:-0}" -eq 1 ] &&
    exec dbus-run-session river > "${XDG_CACHE_HOME}/river.log" 2>&1
