#!/usr/bin/env bash

# Default programs
export BROWSER='firefox'
export EDITOR='nvim'
export TERM='st-256color'
export TERMINAL='st'

# Settings
# Add all directories in `~/.local/bin` to $PATH
export PATH="$PATH:$(find "${HOME}/.local/bin" -type d | paste -sd ':' -)"
export HISTCONTROL='ignoredups'
export QT_QPA_PLATFORMTHEME='gtk2'

export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export INPUTRC="${XDG_CONFIG_HOME}/shell/inputrc"
export XINITRC="${XDG_CONFIG_HOME}/x11/xinitrc"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

[ -z "${DISPLAY}" ] && [ "${XDG_VTNR:-0}" -eq 1 ] &&
    exec startx -- -keeptty >/dev/null 2>&1
