#!/usr/bin/env bash

termcmd="footclient"
termfloat="$termcmd -a term-float"

# Mappings
riverctl map normal Super Return       spawn "$termcmd"
riverctl map normal Super+Shift Return spawn "$termfloat"
riverctl map normal Super W            spawn "firefox"
riverctl map normal Super+Shift W      spawn "firefox --private-window"
riverctl map normal Super E            spawn "$termcmd -e lf"
riverctl map normal Super C            spawn "$termfloat -W 56x8 -o 'font=monospace-14' -e python -qi -c 'from math import *'"
riverctl map normal Super+Shift C      spawn "$termfloat -e nmtui-connect"

riverctl map normal Super Space        spawn "rofi -show run"
riverctl map normal Super+Shift Escape spawn "menu-session"
riverctl map normal Super+Shift S      spawn "menu-screenshot"
riverctl map normal Super+Shift M      spawn "menu-disks mount"
riverctl map normal Super+Shift U      spawn "menu-disks unmount"
riverctl map normal Super+Shift E      spawn "menu-emoji"
riverctl map normal Super+Shift Space  spawn "rofi -show drun -show-icons"

riverctl map normal Super 0            spawn "notify-pulse mute"
riverctl map normal Super Minus        spawn "notify-pulse down"
riverctl map normal Super Equal        spawn "notify-pulse up"
riverctl map normal Super bracketleft  spawn "playerctl previous"
riverctl map normal Super bracketright spawn "playerctl next"
riverctl map normal Super backslash    spawn "playerctl play-pause"

riverctl map normal Super Q close
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super H focus-output left
riverctl map normal Super L focus-output right

riverctl map normal Super+Shift H send-to-output left
riverctl map normal Super+Shift L send-to-output right

riverctl map normal Super I send-layout-cmd rivertile "main-count +1"
riverctl map normal Super D send-layout-cmd rivertile "main-count -1"

riverctl map normal Super+Shift I send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super+Shift D send-layout-cmd rivertile "main-ratio -0.05"

riverctl map normal Super M toggle-fullscreen
riverctl map normal Super F toggle-float

riverctl map normal Super+Control R spawn "${XDG_CONFIG_HOME}/river/init"

for i in $(seq 1 5); do tags=$((1 << (i - 1)))
    riverctl map normal Super "$i"               set-focused-tags "$tags"
    riverctl map normal Super+Shift "$i"         set-view-tags "$tags"
    riverctl map normal Super+Control "$i"       toggle-focused-tags "$tags"
    riverctl map normal Super+Shift+Control "$i" toggle-view-tags "$tags"
done

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# Rules
riverctl rule-add -app-id "*" ssd
riverctl rule-add -app-id "$termcmd" tags 1
riverctl rule-add -app-id "firefox" tags 2
riverctl rule-add -app-id "Soffice" tags 3
riverctl rule-add -app-id "Gimp" tags 3
riverctl rule-add -app-id "Inskcape" tags 3
riverctl rule-add -app-id "*-float" float
riverctl rule-add -app-id "mpv" float
riverctl rule-add -app-id "Nsxiv" float
riverctl rule-add -app-id "steam" float
riverctl rule-add -app-id "steam" -title "Steam" no-float
riverctl rule-add -app-id "firefox" -title "Picture-in-Picture" float

# Options
riverctl background-color       "0x242424"
riverctl border-color-unfocused "0x383838"
riverctl border-color-focused   "0x77767b"
riverctl border-color-urgent    "0xcd9309"
riverctl border-width 1

riverctl focus-follows-cursor normal
riverctl hide-cursor timeout 5000
riverctl hide-cursor when-typing enabled
riverctl set-repeat 50 300
riverctl xcursor-theme "Adwaita"
riverctl keyboard-layout -variant "altgr-intl" -options "ctrl:swapcaps" "us"

riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 -main-ratio 0.5 &

# Autostart
polkit="/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"
polkit_name="polkit-gnome-authentication-agent-1"
riverctl spawn "${XDG_CONFIG_HOME}/display.sh"
riverctl spawn "pidof $polkit_name || $polkit"
riverctl spawn "setbg"
riverctl spawn "pkill waybar; waybar"
riverctl spawn "pkill mako; mako"
riverctl spawn "pidof footclient || pkill foot; foot -s"
