#!/usr/bin/env bash

term="footclient"
term_float="$term -a term-float"
calculator="$term_float -W 56x8 -o 'font=monospace-14' -e python -qic 'from math import *'"

# Mappings
riverctl map normal Super Return       spawn "$term"
riverctl map normal Super+Shift Return spawn "$term_float"
riverctl map normal Super W            spawn "firefox"
riverctl map normal Super E            spawn "$term -e lf"
riverctl map normal Super C            spawn "$calculator"
riverctl map normal Super+Shift C      spawn "$term_float -e nmtui-connect"

riverctl map normal Super Space        spawn "rofi -show drun -show-icons"
riverctl map normal Super+Shift Space  spawn "rofi -show run"
riverctl map normal Super+Shift Escape spawn "menu-session"
riverctl map normal Super+Shift S      spawn "menu-screenshot"
riverctl map normal Super+Shift M      spawn "menu-disks mount"
riverctl map normal Super+Shift U      spawn "menu-disks unmount"
riverctl map normal Super period       spawn "rofi -show emoji"

riverctl map normal Super 0            spawn "notify-pulse mute"
riverctl map normal Super Minus        spawn "notify-pulse down"
riverctl map normal Super Equal        spawn "notify-pulse up"
riverctl map normal Super bracketleft  spawn "playerctl previous"
riverctl map normal Super bracketright spawn "playerctl next"
riverctl map normal Super backslash    spawn "playerctl play-pause"

riverctl map normal Super Q close
riverctl map normal Super M toggle-fullscreen
riverctl map normal Super F toggle-float

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super H focus-output left
riverctl map normal Super L focus-output right

riverctl map normal Super+Shift H send-to-output left
riverctl map normal Super+Shift L send-to-output right

riverctl map normal Super I send-layout-cmd rivertile "main-count +1"
riverctl map normal Super D send-layout-cmd rivertile "main-count -1"

riverctl map normal Super+Shift I send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super+Shift D send-layout-cmd rivertile "main-ratio -0.05"

riverctl map normal Super+Control R spawn "${XDG_CONFIG_HOME}/river/init"

all_tags=$(((1 << 32) - 1))
sticky_tag=$((1 << 31))
all_but_sticky_tag=$(( all_tags ^ sticky_tag ))

riverctl map normal Super S toggle-view-tags $sticky_tag
riverctl spawn-tagmask ${all_but_sticky_tag}

for i in $(seq 1 5); do
    tags=$((1 << (i - 1)))

    riverctl map normal Super "$i"               set-focused-tags $((sticky_tag + tags))
    riverctl map normal Super+Shift "$i"         set-view-tags "$tags"
    riverctl map normal Super+Control "$i"       toggle-focused-tags "$tags"
    riverctl map normal Super+Shift+Control "$i" toggle-view-tags "$tags"
done

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# Rules
riverctl rule-add -app-id "$term" tags 1
riverctl rule-add -app-id 'firefox' tags 2
riverctl rule-add -app-id 'gimp-*' tags 4
riverctl rule-add -app-id 'org.inkscape.Inkscape' tags 4
riverctl rule-add -app-id 'libreoffice-*' tags 4
riverctl rule-add -title  'LibreOffice' tags 4
riverctl rule-add -app-id 'steam' tags 4

riverctl rule-add -app-id '*' ssd
riverctl rule-add -app-id '*-float' float
riverctl rule-add -app-id 'mpv' float
riverctl rule-add -app-id 'viewnior' float
riverctl rule-add -app-id 'firefox' -title 'Picture-in-Picture' float
riverctl rule-add -app-id 'steam' float
riverctl rule-add -app-id 'steam' -title 'Steam' no-float

# Options
source "${HOME}/.config/river/colors"
riverctl border-width 1

riverctl focus-follows-cursor normal
riverctl hide-cursor timeout 5000
riverctl hide-cursor when-typing enabled
riverctl set-repeat 50 300
riverctl xcursor-theme "Adwaita"
riverctl keyboard-layout -variant "altgr-intl" -options "ctrl:swapcaps" "us"

riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 -main-ratio 0.5 &

# Autostart
riverctl spawn "${XDG_CONFIG_HOME}/display.sh"
riverctl spawn 'pidof waybar || waybar'
riverctl spawn 'pidof footclient || pkill foot; foot -s'
riverctl spawn 'swww-daemon'
riverctl spawn 'mako'
riverctl spawn 'nm-applet'
riverctl spawn '/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1'
riverctl spawn 'xrdb "${XDG_CONFIG_HOME}/x11/Xresources"'

# Fix screencasting
# https://wiki.archlinux.org/title/River#Screencasting
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
systemctl --user restart xdg-desktop-portal
