#!/usr/bin/env bash

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
    source "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
    source "${HOME}/.xprofile"
fi

dwmsb.py &
setbg &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

exec dwm
