#!/bin/sh

export PATH="$HOME/.local/bin:$PATH"
export TERM="st-256color"
export EDITOR="nvim"
export HISTCONTROL=ignoredups
export QT_QPA_PLATFORMTHEME="gtk2"
export MEDNAFEN_HOME="$HOME/.local/share/mednafen"

# merge in defaults and keymaps
sysresources="/etc/X11/xinit/.Xresources"
sysmodmap="/etc/X11/xinit/.Xmodmap"
userresources="$HOME/.Xresources"
usermodmap="$HOME/.Xmodmap"

[ -f "$sysresources" ] && xrdb -merge $sysresources
[ -f "$sysmodmap" ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge $userresources
[ -f "$usermodmap" ] && xmodmap $usermodmap

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done; unset f
fi

setxkbmap us altgr-intl
setbg &
dwmstatus.sh &
exec dwm
