#!/usr/bin/env bash

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "${f}" ] && source "${f}"
    done && unset f
fi

xrdb "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources"
setxkbmap us altgr-intl &
dwmsb.py &
setbg &
lxpolkit &

exec dwm
