#!/usr/bin/env bash

set -euo pipefail

rotate() {
    degree="$1"

    for file in "${files[@]}"; do
        mogrify -rotate "$degree" "$file"
    done
}

while read -r file; do
    file="$(realpath "$file")"
    files+=("$file")
done

case "$1" in
    d) # Remove
        nfiles=${#files[@]}

        if (( nfiles > 1 )); then
            prompt="delete ${nfiles} files?"
        else
            prompt="delete '${files[0]##*/}'?"
        fi

        dmenu-prompt "$prompt" && rm "${files[@]}"
        ;;
    e) # Edit
        setsid -f gimp "${files[@]}"
        ;;
    r) # Rotate right
        rotate 90
        ;;
    R) # Rotate left
        rotate 270
        ;;
    w) setbg "${files[@]}" & ;;
    y) # Copy to clipboard
        xclip -selection clipboard -target image/png "${files[@]}"
        ;;
    Y) # Copy paths to clipboard
        printf "'%s' " "${files[@]}" | xclip -selection clipboard
        ;;
    l) # Save to lf copy buffer
        lf_sel_file="${XDG_DATA_HOME:-$HOME/.local/share}/lf/files"
        printf "copy\n" > "$lf_sel_file"
        printf "%s\n" "${files[@]}" >> "$lf_sel_file"
        ;;
esac
