#!/usr/bin/env bash

alias e='nvim'
alias i='nsxiv-rifle'
alias v='mpv'
alias lf='lfub'
alias trans='trans -brief -t es'

alias ls='lsd'
alias la='lsd --almost-all'
alias ll='lsd --long'
alias lla='lsd --long --almost-all'
alias lt='lsd --tree'
alias lta='lsd --tree --almost-all'

alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

ex() { for i in "$@"; do aunpack "$i"; done }
cl() { cd "$1" && ls; }
