#!/usr/bin/env bash

alias e='nvim'
alias i='nsxiv-rifle'
alias v='mpv'
alias lf='lfub'
alias trans='trans -brief -t es'

alias ls='exa --group-directories-first --icons'
alias la='ls --all'
alias ll='ls --long'
alias lla='ls --long --all'
alias lt='ls --tree'
alias lta='ls --tree --all'

alias dots='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

ex() { for i in "$@"; do aunpack "$i"; done }
cl() { cd "$1" && ls; }
