#!/usr/bin/env bash
[[ $- != *i* ]] && return

# Shell options
shopt -s autocd

# Complete options
complete -c man whereis which
complete -cf sudo

# Keybindings
set -o vi

run-help() {
    local command=$(cut -d ' ' -f1 <<< "$READLINE_LINE")

    man "${command}" 2>/dev/null ||
        help "${command}" 2>/dev/null ||
        printf "No manual entry for ${command}\n"
}

bind -m vi-insert -x '"\eh": run-help'
bind -m vi-insert -x '"\C-l": clear'
bind -m vi-insert '"\C-a": beginning-of-line'
bind -m vi-insert '"\C-e": end-of-line'
bind -m vi-insert '"\C-p": history-search-backward'
bind -m vi-insert '"\C-n": history-search-forward'

source "${HOME}/.config/bash/prompt"
source "${HOME}/.config/shell/aliasrc"
