#!/usr/bin/env bash

PROMPT_COMMAND=__bash_prompt

__bash_prompt() {
    local last_exitcode=${?}

    declare -A colors=(
        [black]='\[\e[1;30m\]'
        [red]='\[\e[1;31m\]'
        [green]='\[\e[1;32m\]'
        [yellow]='\[\e[1;33m\]'
        [blue]='\[\e[1;34m\]'
        [purple]='\[\e[1;35m\]'
        [cyan]='\[\e[1;36m\]'
        [white]='\[\e[1;37m\]'
        [reset]='\[\e[0m\]'
    )

    __prompt_cwd() {
        PS1+="${colors[blue]}\W "
    }

    __prompt_git() {
        which git > /dev/null 2>&1 || return

        local branch=$(git rev-parse --abbrev-ref HEAD 2> /dev/null)

        [ "${branch}" ] || return

        PS1+="${colors[white]}at ${colors[red]}${branch} "

        local is_dirty=$(git status --porcelain 2> /dev/null)

        [ "${is_dirty}" ] && PS1+="${colors[yellow]}✗ "
    }

    __prompt_arrow() {
        local arrow_color

        [ ${last_exitcode} -ne 0 ] && arrow_color='red' || arrow_color='green'

        PS1+="${colors[${arrow_color}]}> "
    }

    PS1=""

    __prompt_cwd
    __prompt_git
    __prompt_arrow

    PS1+="${colors[reset]}"
}
