"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 2
final_space = true
console_title_template = "{{ .Shell }} in {{ .Folder }}"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "text"
style = "plain"
foreground = "green"
template = "{{ if .Env.SSH_CLIENT }}<b>{{ .UserName }}@{{ .HostName }}</b> {{ end }}"

[[blocks.segments]]
type = "path"
style = "plain"
foreground = "blue"
template = "<b>{{ .Path }}</b>"

[blocks.segments.properties]
style = "full"

[[blocks.segments]]
type = "git"
style = "plain"
foreground = "red"
templates = [
    "<b>",
    " {{ .HEAD }}",
    "{{ if or .Working.Changed .Staging.Changed .Behind .Ahead }} [{{ end }}",
    "{{ if .Working.Changed }}!{{ end }}",
    "{{ if .Staging.Changed }}+{{ end }}",
    "{{ if gt .Behind 0 }}<{{ end }}",
    "{{ if gt .Ahead 0 }}>{{ end }}",
    "{{ if or .Working.Changed .Staging.Changed .Behind .Ahead }}]{{ end }}",
    "</b>",
]
[blocks.segments.properties]
branch_icon = ""
branch_identical_icon = ""
branch_ahead_icon = ">"
branch_behind_icon = "<"
commit_icon = ""
fetch_status = true

[[blocks.segments]]
type = "python"
style = "plain"
foreground = "yellow"
properties = { display_mode = "context" }
templates = [
    "<b>",
    " Python {{ .Full }}",
    "{{ if .Venv }} ({{.Venv}}){{ end }}",
    "</b>",
]

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "text"
style = "plain"
template = "<b>{{if eq .Code 0}}<green>></>{{else}}<red>x</>{{end}}</b>"

[transient_prompt]
type = "text"
style = "plain"
template = "<b>{{if eq .Code 0}}<green>></>{{else}}<red>x</>{{end}}</b> "

[secondary_prompt]
template = ".... "
