#! /bin/sh

# C O N F I G
bspc monitor -d 1 2 3 4 5
bspc config window_gap            0
bspc config border_width          1
bspc config normal_border_color   \#24283b
bspc config focused_border_color  \#9a7ecc
bspc config presel_feedback_color \#24283b
bspc config focus_follows_pointer true
bspc config borderless_monocle    true
bspc config single_monocle        true

# W I N D O W   R U L E S
bspc rule -a st               desktop="^1"    follow=on
bspc rule -a firefox          desktop="^2"    follow=on
bspc rule -a *:*:ranger       desktop="^3"    follow=on
bspc rule -a Pcmanfm          desktop="^3"    follow=on
bspc rule -a *:*:LibreOffice  desktop="^4"    follow=on
bspc rule -a Soffice          desktop="^4"    follow=on
bspc rule -a Gimp             desktop="^4"    follow=on
bspc rule -a Inkscape         desktop="^4"    follow=on
bspc rule -a discord          desktop="^5"    follow=on

bspc rule -a *:*:ncmpcpp      state=floating  desktop=focused
bspc rule -a feh              state=floating
bspc rule -a firefox:Toolkit  state=floating  sticky=true
bspc rule -a mGBA             state=floating  
bspc rule -a mpv              state=floating  
bspc rule -a Qalculate-gtk    state=floating  sticky=true

# A U T O S T A R T
pkill sxhkd; sxhkd &
xsetroot -cursor_name left_ptr &
~/.config/polybar/launch.sh &
