#!/usr/bin/env bash

normcolor=$(xrdb -get color0)
selcolor=$(xrdb -get accentColor)

# C O N F I G
bspc monitor -d I II III IV V
bspc config window_gap            8
bspc config border_width          1
bspc config normal_border_color   "${normcolor}"
bspc config focused_border_color  "${selcolor}"
bspc config presel_feedback_color "${normcolor}"
bspc config focus_follows_pointer true

# W I N D O W   R U L E S
bspc rule -a St               desktop="^1"
bspc rule -a firefox          desktop="^2"
bspc rule -a *:*:LibreOffice  desktop="^3"
bspc rule -a Soffice          desktop="^3"
bspc rule -a Gimp             desktop="^3"
bspc rule -a Inkscape         desktop="^3"
bspc rule -a discord          desktop="^5"

bspc rule -a firefox:Toolkit  state=floating  sticky=true
bspc rule -a mpv              state=floating  
bspc rule -a Nsxiv            state=floating
bspc rule -a Qalculate-gtk    state=floating  sticky=true

# A U T O S T A R T
xsetroot -cursor_name left_ptr &
pkill sxhkd; sxhkd "${HOME}/.config/sxhkd/bspwm" &
pkill picom; picom &
~/.config/polybar/launch.sh bspwm &
